name: cicd

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

env:
  BUILD_VERSION: ${{ github.sha }}

jobs:

  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [ standalone ]
        os: [ ubuntu ]
    steps:
      - uses: actions/checkout@v4
      - name: Set short SHA version
        run: |
          echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: yrikbush90/docker-android-sdk
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=raw,value=${{ env.SHORT_SHA }},enable=${{ github.ref == format('refs/heads/{0}', 'main') && matrix.os == 'ubuntu' && matrix.flavor == 'standalone' }}
            type=raw,value=android-29,enable=${{ github.ref == format('refs/heads/{0}', 'main') && matrix.os == 'ubuntu' && matrix.flavor == 'standalone' }}
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: int128/kaniko-action@v1
        with:
          push: true
          file: ./Dockerfile
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          cache-repository: yrikbush90/docker-android-sdk
          kaniko-args: |
            --use-new-run 
            --cleanup 
            --compressed-caching=false